import type { Metadata } from "next";
import "./globals.css";
import { Rethink_Sans } from 'next/font/google'
 

const R_sans = Rethink_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={R_sans.className}>
        {children}
      </body>
    </html>
  );
}
